[theme]
# Primary accent color for interactive elements.
primaryColor = "#E6761A"

# Background color for the main content area.
backgroundColor = "#05172F"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#23D0D0"

# Color used for almost all text.
textColor = "#fff"